### ISSUE TITLE
Support for VS2015 Update 3

### ISSUE THREAD

**Issue by jhugard** [boost-experimental/sml#106]
Cannot compile the hello_world example from [here](http://boost-experimental.github.io/sml/examples/index.html#hello-world) using VS2015 Update 3 (version 14.0.25431.01, with C++ 19.00.24215.1).

The same example works fine with VS2017 (version 15.2 (26430.6) Release, with C++ 19.10.25019).

```
1>------ Build started: Project: test_smlAndVs2015, Configuration: Debug Win32 ------
1>  test_smlAndVs2015.cpp
1>d:\work\exploratory\test_smlandvs2015\test_smlandvs2015\boost\sml.hpp(1607): error C2039: 'state_machine': is not a member of 'boost::sml::v1_1_0::back::sm<boost::sml::v1_1_0::back::sm_policy<T>>'
1>          with
1>          [
1>              T=hello_world
1>          ]
1>  d:\work\exploratory\test_smlandvs2015\test_smlandvs2015\boost\sml.hpp(1199): note: see declaration of 'boost::sml::v1_1_0::back::sm<boost::sml::v1_1_0::back::sm_policy<T>>'
1>          with
1>          [
1>              T=hello_world
1>          ]
1>  d:\work\exploratory\test_smlandvs2015\test_smlandvs2015\test_smlandvs2015.cpp(71): note: see reference to class template instantiation 'boost::sml::v1_1_0::sm<hello_world,boost::sml::v1_1_0::Policies<>>' being compiled
1>  d:\work\exploratory\test_smlandvs2015\test_smlandvs2015\test_smlandvs2015.cpp(60): note: see reference to class template instantiation 'boost::sml::v1_1_0::front::state<T>' being compiled
1>          with
1>          [
1>              T=established
1>          ]
1>d:\work\exploratory\test_smlandvs2015\test_smlandvs2015\boost\sml.hpp(1607): error C2873: 'state_machine': symbol cannot be used in a using-declaration
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by jhugard** [comment]
Looks like VS2015 [went broken on AppVeyor](https://ci.appveyor.com/project/krzysztof-jusiak/sml/build/1.0.181/job/v84579yg7kej875l) on 9 Apr 17 with this [commit](https://github.com/boost-experimental/sml/commit/4aef3bfb4fd135683d598ad38915bec23f3692ff).

**Comment by krzysztof-jusiak** [comment]
Fixed by https://github.com/boost-experimental/sml/commit/ca49165220feb55c5ae1903653b0db02e3c37fb5
